#!/usr/bin/env python3

import subprocess
import time
from colorama import Fore,Style,Back
from progress.bar import Bar

#coded by g0dmax55

def bar():
    bar = Bar('Processing', max=100)
    for i in range(100):
        bar.next()
        time.sleep(.01)
    bar.finish()
    print("")

def packages():
    try:
        subprocess.call(["sudo", "apt-get", "clean"])
        subprocess.call(["clear"])
        time.sleep(3)
        print(Fore.RED + "[*] Updateing")
        subprocess.call(["sudo", "apt-get", "update"])
        bar()
        print("[*] Upgrading")
        subprocess.call(["sudo", "apt-get", "upgrade", "-y"])
        bar()
        print("[*] Dist-Upgrading")
        subprocess.call(["sudo", "apt-get", "dist-upgrade", "-y"])
        bar()
        print("[+] Installing Wget")
        subprocess.call(["sudo", "apt-get", "install", "wget", "-y"])
        bar()
        print("[+] Installing Net-Tools")
        subprocess.call(["sudo", "apt-get", "install", "net-tools", "-y"])
        bar()
        print("[+] Installing Gpg")
        subprocess.call(["sudo", "apt-get", "install", "gpg", "-y"])
        bar()
        print("[+] Installing Vs-Code")
        subprocess.call(["wget", "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64", "-O", "code.deb"])
        subprocess.call(["sudo", "apt-get", "install", "-f", "./code.deb"])
        subprocess.call(["rm", "code.deb"])
        bar()
        print("[+] Installing Nmap")
        subprocess.call(["sudo", "apt-get", "install", "nmap", "-y"])
        bar()
        print("[+] Installing Sublime")
        subprocess.call(["wget", "https://download.sublimetext.com/sublime-text_build-3211_amd64.deb", "-O", "sublime.deb"])
        subprocess.call(["sudo", "apt-get", "install", "-f", "./sublime.deb"])
        subprocess.call(["rm", "sublime.deb"])
        bar()
        print("[+] Installing Tshark")
        subprocess.call(["sudo", "apt-get", "install", "tshark", "-y"])
        bar()
        print("[+] Installing Fuzz")
        subprocess.call(["sudo", "apt-get", "install", "fuzz", "-y"])
        bar()
        print("[+] Installing Terminator")
        subprocess.call(["sudo", "apt-get", "install", "terminator", "-y"])
        bar()
        print("[+] Installing Metasploit")
        subprocess.call(["wget", "https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb", "-O", "msfinstall"])
        subprocess.call(["chmod", "+x", "msfinstall"])
        subprocess.call(["./msfinstall"])
        subprocess.call(["rm", "msfinstall"])
        bar()
        print("[+] Installing Hydra")
        subprocess.call(["sudo", "apt-get", "install", "hydra", "-y"])
        bar()
        print("[+] Installing Curl")
        subprocess.call(["sudo", "apt-get", "install", "curl", "-y"])
        bar()
        print("[+] Installing John")
        subprocess.call(["sudo", "apt-get", "install", "john", "-y"])
        bar()
        print("[+] Installing Hashcat")
        subprocess.call(["sudo", "apt-get", "install", "hashcat", "-y"])
        bar()
        print("[+] Installing Bmon")
        subprocess.call(["sudo", "apt-get", "install", "bmon", "-y"])
        bar()
        print("[+] Installing Wireshark")
        subprocess.call(["sudo", "apt-get", "install", "wireshark", "-y"])
        bar()
        print("[+] Installing Bashtop")
        subprocess.call(["sudo", "apt-get", "install", "bashtop", "-y"])
        bar()
        print("[+] Installing Aircrack-Ng")
        subprocess.call(["sudo", "apt-get", "install", "aircrack-ng", "-y"])
        bar()
        print("[+] Installing Wifite")
        subprocess.call(["sudo", "apt-get", "install", "wifite", "-y"])
        bar()
        print("[+] Installing Netcat")
        subprocess.call(["sudo", "apt-get", "install", "netcat", "-y"])
        bar()
        print("[+] Installing Tor")
        subprocess.call(["sudo", "apt-get", "install", "tor", "-y"])
        bar()
        print("[+] Installing Proxy-Chains")
        subprocess.call(["sudo", "apt-get", "install", "proxychains", "-y"])
        bar()
        time.sleep(3)
        print("[*] Finish")

    except KeyboardInterrupt:
        print("")

packages()


